import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { axiosClient } from "@/lib/axios-client";

export interface ThemeResponse {
  name: string;
  lightTheme: Record<string, string>;
  darkTheme: Record<string, string>;
}

export const COLOR_VARIABLES = [
  { key: "--background", label: "Background" },
  { key: "--foreground", label: "Foreground" },
  { key: "--primary", label: "Primary" },
  { key: "--primary-foreground", label: "Primary Foreground" },
  { key: "--card", label: "Card" },
  { key: "--card-foreground", label: "Card Foreground" },
  { key: "--popover", label: "Popover" },
  { key: "--popover-foreground", label: "Popover Foreground" },
  { key: "--secondary", label: "Secondary" },
  { key: "--secondary-foreground", label: "Secondary Foreground" },
  { key: "--muted", label: "Muted" },
  { key: "--muted-foreground", label: "Muted Foreground" },
  { key: "--accent", label: "Accent" },
  { key: "--accent-foreground", label: "Accent Foreground" },
  { key: "--destructive", label: "Destructive" },
  { key: "--destructive-foreground", label: "Destructive Foreground" },
  { key: "--border", label: "Border" },
  { key: "--input", label: "Input" },
  { key: "--ring", label: "Ring" },
  { key: "--sidebar", label: "Sidebar Background" },
  { key: "--sidebar-foreground", label: "Sidebar Foreground" },
  { key: "--sidebar-primary", label: "Sidebar Primary" },
  { key: "--sidebar-primary-foreground", label: "Sidebar Primary Foreground" },
  { key: "--sidebar-accent", label: "Sidebar Accent" },
  { key: "--sidebar-accent-foreground", label: "Sidebar Accent Foreground" },
  { key: "--sidebar-border", label: "Sidebar Border" },
  { key: "--sidebar-ring", label: "Sidebar Ring" },
  { key: "--info", label: "Info" },
  { key: "--info-foreground", label: "Info Foreground" },
  { key: "--success", label: "Success" },
  { key: "--success-foreground", label: "Success Foreground" },
  { key: "--warning", label: "Warning" },
  { key: "--warning-foreground", label: "Warning Foreground" },
  { key: "--invert", label: "Invert" },
  { key: "--invert-foreground", label: "Invert Foreground" },
  { key: "--color-dv-primary", label: "Video Player Primary" },
  { key: "--color-dv-hover", label: "Video Player Hover" },
  { key: "--color-dv-bg", label: "Video Player Background" },
  { key: "--color-dv-surface", label: "Video Player Surface" },
  { key: "--color-dv-text", label: "Video Player Text" },
  { key: "--color-dv-text-muted", label: "Video Player Text Muted" },
];

export function useTheme() {
  return useQuery<ThemeResponse>({
    queryKey: ["theme"],
    queryFn: async () => {
      const { data } = await axiosClient.get<ThemeResponse>("/public/theme");
      return data;
    },
  });
}

export function useUpdateTheme() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (payload: {
      name: string;
      lightTheme: Record<string, string>;
      darkTheme: Record<string, string>;
    }) => {
      const { data } = await axiosClient.post("/admin/theme", payload);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["theme"] });
    },
  });
}

export interface ThemePreset {
  name: string;
  lightTheme: Record<string, string>;
  darkTheme: Record<string, string>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: "Default (Slate/Zinc)",
    lightTheme: {
      "--background": "oklch(1 0 0)",
      "--foreground": "oklch(0.145 0 0)",
      "--card": "oklch(1 0 0)",
      "--card-foreground": "oklch(0.145 0 0)",
      "--popover": "oklch(1 0 0)",
      "--popover-foreground": "oklch(0.145 0 0)",
      "--primary": "oklch(0.205 0 0)",
      "--primary-foreground": "oklch(0.985 0 0)",
      "--secondary": "oklch(0.97 0 0)",
      "--secondary-foreground": "oklch(0.205 0 0)",
      "--muted": "oklch(0.97 0 0)",
      "--muted-foreground": "oklch(0.556 0 0)",
      "--accent": "oklch(0.97 0 0)",
      "--accent-foreground": "oklch(0.205 0 0)",
      "--destructive": "oklch(0.58 0.22 27)",
      "--border": "oklch(0.922 0 0)",
      "--input": "oklch(0.922 0 0)",
      "--ring": "oklch(0.708 0 0)",
      "--sidebar": "oklch(0.985 0 0)",
      "--sidebar-foreground": "oklch(0.145 0 0)",
      "--sidebar-primary": "oklch(0.205 0 0)",
      "--sidebar-primary-foreground": "oklch(0.985 0 0)",
      "--sidebar-accent": "oklch(0.97 0 0)",
      "--sidebar-accent-foreground": "oklch(0.205 0 0)",
      "--sidebar-border": "oklch(0.922 0 0)",
      "--sidebar-ring": "oklch(0.708 0 0)",
      "--info": "var(--color-violet-500)",
      "--info-foreground": "var(--color-violet-900)",
      "--success": "var(--color-emerald-500)",
      "--success-foreground": "var(--color-emerald-900)",
      "--warning": "var(--color-yellow-500)",
      "--warning-foreground": "var(--color-yellow-900)",
      "--invert": "var(--color-zinc-900)",
      "--invert-foreground": "var(--color-zinc-50)",
      "--color-dv-primary": "oklch(0.627 0.265 29.866)",
      "--color-dv-hover": "oklch(0.527 0.265 29.866)",
      "--color-dv-bg": "oklch(0.1 0 0)",
      "--color-dv-surface": "oklch(0.15 0 0)",
      "--color-dv-text": "oklch(0.985 0 0)",
      "--color-dv-text-muted": "oklch(0.708 0 0)",
    },
    darkTheme: {
      "--background": "oklch(0.145 0 0)",
      "--foreground": "oklch(0.985 0 0)",
      "--card": "oklch(0.205 0 0)",
      "--card-foreground": "oklch(0.985 0 0)",
      "--popover": "oklch(0.205 0 0)",
      "--popover-foreground": "oklch(0.985 0 0)",
      "--primary": "oklch(0.87 0 0)",
      "--primary-foreground": "oklch(0.205 0 0)",
      "--secondary": "oklch(0.269 0 0)",
      "--secondary-foreground": "oklch(0.985 0 0)",
      "--muted": "oklch(0.269 0 0)",
      "--muted-foreground": "oklch(0.708 0 0)",
      "--accent": "oklch(0.371 0 0)",
      "--accent-foreground": "oklch(0.985 0 0)",
      "--destructive": "oklch(0.704 0.191 22.216)",
      "--border": "oklch(1 0 0 / 10%)",
      "--input": "oklch(1 0 0 / 15%)",
      "--ring": "oklch(0.556 0 0)",
      "--sidebar": "oklch(0.205 0 0)",
      "--sidebar-foreground": "oklch(0.985 0 0)",
      "--sidebar-primary": "oklch(0.488 0.243 264.376)",
      "--sidebar-primary-foreground": "oklch(0.985 0 0)",
      "--sidebar-accent": "oklch(0.269 0 0)",
      "--sidebar-accent-foreground": "oklch(0.985 0 0)",
      "--sidebar-border": "oklch(1 0 0 / 10%)",
      "--sidebar-ring": "oklch(0.556 0 0)",
      "--info": "var(--color-violet-500)",
      "--info-foreground": "var(--color-violet-600)",
      "--success": "var(--color-emerald-500)",
      "--success-foreground": "var(--color-emerald-600)",
      "--warning": "var(--color-yellow-500)",
      "--warning-foreground": "var(--color-yellow-600)",
      "--invert": "var(--color-zinc-700)",
      "--invert-foreground": "var(--color-zinc-50)",
      "--color-dv-primary": "oklch(0.627 0.265 29.866)",
      "--color-dv-hover": "oklch(0.527 0.265 29.866)",
      "--color-dv-bg": "oklch(0.1 0 0)",
      "--color-dv-surface": "oklch(0.15 0 0)",
      "--color-dv-text": "oklch(0.985 0 0)",
      "--color-dv-text-muted": "oklch(0.708 0 0)",
    },
  },
  {
    name: "Ocean Breeze (Blue)",
    lightTheme: {
      "--background": "#f0f9ff",
      "--foreground": "#0f172a",
      "--card": "#ffffff",
      "--card-foreground": "#0f172a",
      "--popover": "#ffffff",
      "--popover-foreground": "#0f172a",
      "--primary": "#0284c7",
      "--primary-foreground": "#ffffff",
      "--secondary": "#e0f2fe",
      "--secondary-foreground": "#0369a1",
      "--muted": "#f1f5f9",
      "--muted-foreground": "#64748b",
      "--accent": "#f1f5f9",
      "--accent-foreground": "#0f172a",
      "--destructive": "#ef4444",
      "--border": "#e2e8f0",
      "--input": "#e2e8f0",
      "--ring": "#0284c7",
      "--sidebar": "#ffffff",
      "--sidebar-foreground": "#0f172a",
      "--sidebar-primary": "#0284c7",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#f1f5f9",
      "--sidebar-accent-foreground": "#0f172a",
      "--sidebar-border": "#e2e8f0",
      "--sidebar-ring": "#0284c7",
      "--info": "#06b6d4",
      "--info-foreground": "#ffffff",
      "--success": "#10b981",
      "--success-foreground": "#ffffff",
      "--warning": "#f59e0b",
      "--warning-foreground": "#ffffff",
      "--invert": "#0f172a",
      "--invert-foreground": "#ffffff",
      "--color-dv-primary": "#0284c7",
      "--color-dv-hover": "#0369a1",
      "--color-dv-bg": "#0f172a",
      "--color-dv-surface": "#1e293b",
      "--color-dv-text": "#ffffff",
      "--color-dv-text-muted": "#94a3b8",
    },
    darkTheme: {
      "--background": "#0b1329",
      "--foreground": "#f8fafc",
      "--card": "#111c44",
      "--card-foreground": "#f8fafc",
      "--popover": "#111c44",
      "--popover-foreground": "#f8fafc",
      "--primary": "#38bdf8",
      "--primary-foreground": "#0b1329",
      "--secondary": "#1e293b",
      "--secondary-foreground": "#f8fafc",
      "--muted": "#1e293b",
      "--muted-foreground": "#94a3b8",
      "--accent": "#1e293b",
      "--accent-foreground": "#f8fafc",
      "--destructive": "#f87171",
      "--border": "#1e293b",
      "--input": "#1e293b",
      "--ring": "#38bdf8",
      "--sidebar": "#111c44",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#38bdf8",
      "--sidebar-primary-foreground": "#0b1329",
      "--sidebar-accent": "#1e293b",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#1e293b",
      "--sidebar-ring": "#38bdf8",
      "--info": "#38bdf8",
      "--info-foreground": "#0b1329",
      "--success": "#34d399",
      "--success-foreground": "#0b1329",
      "--warning": "#fbbf24",
      "--warning-foreground": "#0b1329",
      "--invert": "#1e293b",
      "--invert-foreground": "#f8fafc",
      "--color-dv-primary": "#38bdf8",
      "--color-dv-hover": "#0284c7",
      "--color-dv-bg": "#0b1329",
      "--color-dv-surface": "#111c44",
      "--color-dv-text": "#f8fafc",
      "--color-dv-text-muted": "#94a3b8",
    },
  },
  {
    name: "Forest Emerald (Green)",
    lightTheme: {
      "--background": "#f0fdf4",
      "--foreground": "#0f172a",
      "--card": "#ffffff",
      "--card-foreground": "#0f172a",
      "--popover": "#ffffff",
      "--popover-foreground": "#0f172a",
      "--primary": "#16a34a",
      "--primary-foreground": "#ffffff",
      "--secondary": "#dcfce7",
      "--secondary-foreground": "#15803d",
      "--muted": "#f1f5f9",
      "--muted-foreground": "#64748b",
      "--accent": "#f1f5f9",
      "--accent-foreground": "#0f172a",
      "--destructive": "#ef4444",
      "--border": "#e2e8f0",
      "--input": "#e2e8f0",
      "--ring": "#16a34a",
      "--sidebar": "#ffffff",
      "--sidebar-foreground": "#0f172a",
      "--sidebar-primary": "#16a34a",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#f1f5f9",
      "--sidebar-accent-foreground": "#0f172a",
      "--sidebar-border": "#e2e8f0",
      "--sidebar-ring": "#16a34a",
      "--info": "#06b6d4",
      "--info-foreground": "#ffffff",
      "--success": "#10b981",
      "--success-foreground": "#ffffff",
      "--warning": "#f59e0b",
      "--warning-foreground": "#ffffff",
      "--invert": "#0f172a",
      "--invert-foreground": "#ffffff",
      "--color-dv-primary": "#16a34a",
      "--color-dv-hover": "#15803d",
      "--color-dv-bg": "#0f172a",
      "--color-dv-surface": "#1e293b",
      "--color-dv-text": "#ffffff",
      "--color-dv-text-muted": "#94a3b8",
    },
    darkTheme: {
      "--background": "#051e15",
      "--foreground": "#f0fdf4",
      "--card": "#093a28",
      "--card-foreground": "#f0fdf4",
      "--popover": "#093a28",
      "--popover-foreground": "#f0fdf4",
      "--primary": "#34d399",
      "--primary-foreground": "#051e15",
      "--secondary": "#115e42",
      "--secondary-foreground": "#f0fdf4",
      "--muted": "#115e42",
      "--muted-foreground": "#a7f3d0",
      "--accent": "#115e42",
      "--accent-foreground": "#f0fdf4",
      "--destructive": "#f87171",
      "--border": "#115e42",
      "--input": "#115e42",
      "--ring": "#34d399",
      "--sidebar": "#093a28",
      "--sidebar-foreground": "#f0fdf4",
      "--sidebar-primary": "#34d399",
      "--sidebar-primary-foreground": "#051e15",
      "--sidebar-accent": "#115e42",
      "--sidebar-accent-foreground": "#f0fdf4",
      "--sidebar-border": "#115e42",
      "--sidebar-ring": "#34d399",
      "--info": "#22d3ee",
      "--info-foreground": "#051e15",
      "--success": "#34d399",
      "--success-foreground": "#051e15",
      "--warning": "#fbbf24",
      "--warning-foreground": "#051e15",
      "--invert": "#115e42",
      "--invert-foreground": "#f0fdf4",
      "--color-dv-primary": "#34d399",
      "--color-dv-hover": "#059669",
      "--color-dv-bg": "#051e15",
      "--color-dv-surface": "#093a28",
      "--color-dv-text": "#f0fdf4",
      "--color-dv-text-muted": "#a7f3d0",
    },
  },
];

